"""primera migracion

Revision ID: f59eb8292c7e
Revises: 
Create Date: 2026-08-27 22:09:17.045268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59eb8292c7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CUPONES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_CUPONES_id'), 'CUPONES', ['id'], unique=False)
    op.create_table('MEDIOS_PAGO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medio_pago', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medio_pago')
    )
    op.create_index(op.f('ix_MEDIOS_PAGO_id'), 'MEDIOS_PAGO', ['id'], unique=False)
    op.create_table('PRODUCTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor_puntos', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PRODUCTOS_id'), 'PRODUCTOS', ['id'], unique=False)
    op.create_table('PROVEEDORES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=150), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('barrio', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PROVEEDORES_id'), 'PROVEEDORES', ['id'], unique=False)
    op.create_table('ROLES_ADM',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol')
    )
    op.create_index(op.f('ix_ROLES_ADM_id'), 'ROLES_ADM', ['id'], unique=False)
    op.create_table('ROLES_CLI',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol')
    )
    op.create_index(op.f('ix_ROLES_CLI_id'), 'ROLES_CLI', ['id'], unique=False)
    op.create_table('STOCK',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('cantidad_minima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_STOCK_id'), 'STOCK', ['id'], unique=False)
    op.create_table('TIPOS_MOVIMIENTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_index(op.f('ix_TIPOS_MOVIMIENTOS_id'), 'TIPOS_MOVIMIENTOS', ['id'], unique=False)
    op.create_table('MOVIMIENTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['TIPOS_MOVIMIENTOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MOVIMIENTOS_id'), 'MOVIMIENTOS', ['id'], unique=False)
    op.create_table('PRODUCTO_COMPOSICION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('cantidad_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['PRODUCTOS.id'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['STOCK.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PRODUCTO_COMPOSICION_id'), 'PRODUCTO_COMPOSICION', ['id'], unique=False)
    op.create_table('STOCK_X_PROVEEDORES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['PROVEEDORES.id'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['STOCK.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_STOCK_X_PROVEEDORES_id'), 'STOCK_X_PROVEEDORES', ['id'], unique=False)
    op.create_table('USUARIOS_ADM',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=50), nullable=False),
    sa.Column('rol_adm_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rol_adm_id'], ['ROLES_ADM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_USUARIOS_ADM_id'), 'USUARIOS_ADM', ['id'], unique=False)
    op.create_table('USUARIOS_CLI',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_cli_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('fecha_nac', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rol_cli_id'], ['ROLES_CLI.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_USUARIOS_CLI_id'), 'USUARIOS_CLI', ['id'], unique=False)
    op.create_table('MEDIOS_PAGO_X_MOVIMIENTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['MEDIOS_PAGO.id'], ),
    sa.ForeignKeyConstraint(['id_movimiento'], ['MOVIMIENTOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MEDIOS_PAGO_X_MOVIMIENTOS_id'), 'MEDIOS_PAGO_X_MOVIMIENTOS', ['id'], unique=False)
    op.create_table('MOVIMIENTOS_COMPRA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('detalle', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_movimiento'], ['MOVIMIENTOS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_movimiento')
    )
    op.create_index(op.f('ix_MOVIMIENTOS_COMPRA_id'), 'MOVIMIENTOS_COMPRA', ['id'], unique=False)
    op.create_table('MOVIMIENTOS_GASTO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('detalle', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['MOVIMIENTOS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id')
    )
    op.create_index(op.f('ix_MOVIMIENTOS_GASTO_id'), 'MOVIMIENTOS_GASTO', ['id'], unique=False)
    op.create_table('PUNTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_cli_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_cli_id'], ['USUARIOS_CLI.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PUNTOS_id'), 'PUNTOS', ['id'], unique=False)
    op.create_table('TURNOS_CAJA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_adm_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.DateTime(), nullable=False),
    sa.Column('fecha_hasta', sa.DateTime(), nullable=True),
    sa.Column('abierto', sa.Boolean(), nullable=False),
    sa.Column('efectivo_inicial', sa.Float(), nullable=False),
    sa.Column('observacion_apertura', sa.String(length=100), nullable=False),
    sa.Column('observacion_cierre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_adm_id'], ['USUARIOS_ADM.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TURNOS_CAJA_id'), 'TURNOS_CAJA', ['id'], unique=False)
    op.create_table('MOVIMIENTOS_VENTAS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movimiento_id'], ['MOVIMIENTOS.id'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['TURNOS_CAJA.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id')
    )
    op.create_index(op.f('ix_MOVIMIENTOS_VENTAS_id'), 'MOVIMIENTOS_VENTAS', ['id'], unique=False)
    op.create_table('STOCK_X_MOVIMIENTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mov_compra', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_mov_compra'], ['MOVIMIENTOS_COMPRA.id'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['STOCK.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_STOCK_X_MOVIMIENTOS_id'), 'STOCK_X_MOVIMIENTOS', ['id'], unique=False)
    op.create_table('CUPONES_USUARIO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_cli_id', sa.Integer(), nullable=False),
    sa.Column('cupon_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_venta_id', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cupon_id'], ['CUPONES.id'], ),
    sa.ForeignKeyConstraint(['movimiento_venta_id'], ['MOVIMIENTOS_VENTAS.id'], ),
    sa.ForeignKeyConstraint(['usuario_cli_id'], ['USUARIOS_CLI.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CUPONES_USUARIO_id'), 'CUPONES_USUARIO', ['id'], unique=False)
    op.create_table('PRODUCTOS_X_MOVIMIENTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_movimiento_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_movimiento_venta'], ['MOVIMIENTOS_VENTAS.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['PRODUCTOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PRODUCTOS_X_MOVIMIENTOS_id'), 'PRODUCTOS_X_MOVIMIENTOS', ['id'], unique=False)
    # ### end Alembic commands ###

     # Seed: ROLES_ADM
    roles_adm_table = sa.table('ROLES_ADM',
        sa.column('id', sa.Integer),
        sa.column('rol', sa.String)
    )
    op.bulk_insert(roles_adm_table, [
        {'id': 0, 'rol': 'DEV'},
        {'id': 1, 'rol': 'ADMIN'},
        {'id': 2, 'rol': 'CAJERO'}
    ])

    # Seed: ROLES_CLI
    roles_cli_table = sa.table('ROLES_CLI',
        sa.column('id', sa.Integer),
        sa.column('rol', sa.String)
    )
    op.bulk_insert(roles_cli_table, [
        {'id': 1, 'rol': 'CLIENTE'}
    ])

    # Seed: TIPOS_MOVIMIENTOS
    tipos_table = sa.table('TIPOS_MOVIMIENTOS',
        sa.column('id', sa.Integer),
        sa.column('tipo', sa.String)
    )
    op.bulk_insert(tipos_table, [
        {'id': 1, 'tipo': 'VENTA'},
        {'id': 2, 'tipo': 'COMPRA'},
        {'id': 3, 'tipo': 'GASTO'}
    ])

    # Seed: MEDIOS_PAGO
    medios_pago_table = sa.table('MEDIOS_PAGO',
        sa.column('id', sa.Integer),
        sa.column('medio_pago', sa.String)
    )
    op.bulk_insert(medios_pago_table, [
        {'id': 1, 'medio_pago': 'EFECTIVO'},
        {'id': 2, 'medio_pago': 'MERCADO_PAGO'},
        {'id': 3, 'medio_pago': 'TARJETA_DEBITO'},
        {'id': 4, 'medio_pago': 'TARJETA_CREDITO'}
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PRODUCTOS_X_MOVIMIENTOS_id'), table_name='PRODUCTOS_X_MOVIMIENTOS')
    op.drop_table('PRODUCTOS_X_MOVIMIENTOS')
    op.drop_index(op.f('ix_CUPONES_USUARIO_id'), table_name='CUPONES_USUARIO')
    op.drop_table('CUPONES_USUARIO')
    op.drop_index(op.f('ix_STOCK_X_MOVIMIENTOS_id'), table_name='STOCK_X_MOVIMIENTOS')
    op.drop_table('STOCK_X_MOVIMIENTOS')
    op.drop_index(op.f('ix_MOVIMIENTOS_VENTAS_id'), table_name='MOVIMIENTOS_VENTAS')
    op.drop_table('MOVIMIENTOS_VENTAS')
    op.drop_index(op.f('ix_TURNOS_CAJA_id'), table_name='TURNOS_CAJA')
    op.drop_table('TURNOS_CAJA')
    op.drop_index(op.f('ix_PUNTOS_id'), table_name='PUNTOS')
    op.drop_table('PUNTOS')
    op.drop_index(op.f('ix_MOVIMIENTOS_GASTO_id'), table_name='MOVIMIENTOS_GASTO')
    op.drop_table('MOVIMIENTOS_GASTO')
    op.drop_index(op.f('ix_MOVIMIENTOS_COMPRA_id'), table_name='MOVIMIENTOS_COMPRA')
    op.drop_table('MOVIMIENTOS_COMPRA')
    op.drop_index(op.f('ix_MEDIOS_PAGO_X_MOVIMIENTOS_id'), table_name='MEDIOS_PAGO_X_MOVIMIENTOS')
    op.drop_table('MEDIOS_PAGO_X_MOVIMIENTOS')
    op.drop_index(op.f('ix_USUARIOS_CLI_id'), table_name='USUARIOS_CLI')
    op.drop_table('USUARIOS_CLI')
    op.drop_index(op.f('ix_USUARIOS_ADM_id'), table_name='USUARIOS_ADM')
    op.drop_table('USUARIOS_ADM')
    op.drop_index(op.f('ix_STOCK_X_PROVEEDORES_id'), table_name='STOCK_X_PROVEEDORES')
    op.drop_table('STOCK_X_PROVEEDORES')
    op.drop_index(op.f('ix_PRODUCTO_COMPOSICION_id'), table_name='PRODUCTO_COMPOSICION')
    op.drop_table('PRODUCTO_COMPOSICION')
    op.drop_index(op.f('ix_MOVIMIENTOS_id'), table_name='MOVIMIENTOS')
    op.drop_table('MOVIMIENTOS')
    op.drop_index(op.f('ix_TIPOS_MOVIMIENTOS_id'), table_name='TIPOS_MOVIMIENTOS')
    op.drop_table('TIPOS_MOVIMIENTOS')
    op.drop_index(op.f('ix_STOCK_id'), table_name='STOCK')
    op.drop_table('STOCK')
    op.drop_index(op.f('ix_ROLES_CLI_id'), table_name='ROLES_CLI')
    op.drop_table('ROLES_CLI')
    op.drop_index(op.f('ix_ROLES_ADM_id'), table_name='ROLES_ADM')
    op.drop_table('ROLES_ADM')
    op.drop_index(op.f('ix_PROVEEDORES_id'), table_name='PROVEEDORES')
    op.drop_table('PROVEEDORES')
    op.drop_index(op.f('ix_PRODUCTOS_id'), table_name='PRODUCTOS')
    op.drop_table('PRODUCTOS')
    op.drop_index(op.f('ix_MEDIOS_PAGO_id'), table_name='MEDIOS_PAGO')
    op.drop_table('MEDIOS_PAGO')
    op.drop_index(op.f('ix_CUPONES_id'), table_name='CUPONES')
    op.drop_table('CUPONES')
    # ### end Alembic commands ###
